[META]
app_package = PTTimeline
app_name = PTTPlot
app_version = 0.5.0-dev.9
ini_version = 2

[DEBUGGING]
enabled_bool = False
filename = pttplot.dbg

[EXTERNAL_PROGRAMS]
python_exe = python
viewer_py = pttview.py
viewer_exe = pttview.exe
pdf_viewer_py = pttview.py
pdf_viewer_exe = pttview.exe
svg_viewer_py = pttview.py
svg_viewer_exe = pttview.exe

[BACKUPS]
backups_on_bool = True
backups_folder = ptt_backups
backups_max_int = 100

[PLOTTING]
window_maximized_bool = False
title_text = Process-Task Timeline
x_axis_label = Time
y_axis_label = Processes
set_major_locator_float = 1
set_minor_locator_float = 0
x_axis_min_float = None
x_axis_max_float = None
exclude_hbar_groups = [""]
save_dpi_int = 300

[PRESENTATION]
hbar_stacking = Unstacked
hbar_label_justified = Center
hbar_label_rotation = Horizontal
dependency_arrow_mode = Time
show_predecessors_bool = False
show_successors_bool = False

[COLORS]
color_list = 
	#1f77b4,
	#aec7e8,
	#ff7f0e,
	#ffbb78,
	#2ca02c,
	#98df8a,
	#d62728,
	#ff9896,
	#9467bd,
	#c5b0d5,
	#8c564b,
	#c49c94,
	#e377c2,
	#f7b6d2,
	#7f7f7f,
	#c7c7c7,
	#bcbd22,
	#dbdb8d,
	#17becf,
	#9edae5

[ANNOTATIONS.MARKER_DEFAULTS]
linestyle = dashed
linewidth_float = 1
color = red
fontsize_float = 7
fontstyle = normal
position = top
rotation_float = 0

[ANNOTATIONS.MARKERS]

[RECENT_FILES_PTTD]
file_0 = D:\Users\Richa\Code\Python\PTTimeline\PTTimeline_Dev\test_samples\robotic_pipettor_v5.pttd

[RECENT_FILES_PTTP]
file_0 = D:\Users\Richa\Code\Python\PTTimeline\PTTimeline_Dev\test_samples\robotic_pipettor_v5.{}.pttp

